---

- name: manage vagrant ssh keys and set password to 'vagrant'
  user:
    name: vagrant
    generate_ssh_key: yes
  register: vagrant_id_rsa

- name: install vagrant public key as authorized_key for vagrant user
  authorized_key:
    user: vagrant
    key: "{{ vagrant_id_rsa.ssh_public_key }}"

- name: install vagrant public key as authorized_key for root user
  authorized_key:
    user: root
    key: "{{ vagrant_id_rsa.ssh_public_key }}"

- name: install vagrant insecure authorized-key
  authorized_key:
    user: vagrant
    key: |
      ssh-rsa AAAAB3NzaC1yc2EAAAABIwAAAQEA6NF8iallvQVp22WDkTkyrtvp9eWW6A8YVr+kz4TjGYe7gHzIw+niNltGEFHzD8+v1I2YJ6oXevct1YeS0o9HZyN1Q9qgCgzUFtdOKLv6IedplqoPkcmF0aYet2PkEDo3MlTBckFXPITAMzF8dJSIFo9D8HfdOV0IAdx4O7PtixWKn5y2hMNG0zQPyUecp4pzC6kivAIhyfHilFR61RGL+GPXQ2MWZWFYbAGjyiYJnAmCP3NOTd0jMZEnDkbUvxhMmBYSdETk1rRgm+R4LOzFUGaHqHDLKLX+FIPKcF96hrucXzcWyLbIbEgE98OHlnVYCzRdK8jlqm8tehUc9c9WhQ== vagrant insecure public key

- name: create ssh config for vagrant user
  copy:
    src: ssh_config
    dest: /home/vagrant/.ssh/config
    mode: 0400
    owner: vagrant
    group: vagrant

...
